// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xouxjwrfohpioiydyjzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdXhqd3Jmb2hwaW9peWR5anpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDAxMDIsImV4cCI6MjA1NzM3NjEwMn0.YuoZbjqwtbIuBPMR5lcutsOq4CLSGpRkP_fE5if-lrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);